### ISSUE TITLE
sqlcipher version upgrade

### ISSUE THREAD

**Issue by mmkrishna2008** [project-imas/encrypted-core-data#182]
Hi,

We are using encrypted-core-data in our app and its working fine without any issues. We are getting build errors related to sqlcipher while builidng sqlcipher target in xcode.

I know this issue is not related to encrypted-core-data. But we would like to know if any one of the users have faced build errors issue while building dependent sqlcipher project in xcode.

If we build sqlcipher 3.1.0 for simulator it is working fine but its failing for iOS device or actual device.
I have downloaded latest sqlcipher 3.3.0 and able to build the project in Xcode for both simulator and device.

It seems sqlcipher version 3.1.0 is not working fine Xcode 6.1 and iOS 8. 

Here are logs copied from Xcode build
---------------------------------------------------
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk/usr/include/stdio.h:64:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk/usr/include/sys/cdefs.h:680:2: error: Unsupported architecture
#error Unsupported architecture
 ^
In file included from ./tool/mkkeywordhash.c:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk/usr/include/stdio.h:67:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk/usr/include/_types.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk/usr/include/sys/_types.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
#error architecture not supported
 ^
-----------------------------------------
Does encrypted-core-data will work for sqlcipher-3.3.0 or not?

Did anyone face this issue while building sqlcipher 3.1.0 in Xcode 6.x?

Thanks,
Krish

**Comment by dorada** [comment]
I can successfully build against sqlcipher 3.3 on Xcode7

**Comment by gavin-black** [comment]
Hi @mmkrishna2008 

Checked here too, and it seems to also work with sqlcipher 3.3.  Let me know if you upgrade Xcode to the latest and it's still failing, since I'd like to upgrade the pod spec to use 3.3 soon.
